### PR TITLE
option 1 for pastebin stage integration & structure

### PR DESCRIPTION
**Pull request by cmharlow**
Jira: https://mozilla-hub.atlassian.net/browse/SE-1994

notes:
* if you're too busy to review, this can sit. its just cleanup & low-hanging fruit changes while working on this. 
* it is one alternative; either we choose this route or #65 (or neither, but we don't choose both)
* #66 is independent of these options and reviewed separately;
* the workflow here: you'd change into the directory of the application or shared infrastructure you were working on; run tf commands there; etc. later on, could use some tooling to help automate this (e.g. workspaces & pointing to directories for application & environments we wish to change; or something like terragrunt).

What this PR does:
* adds pastebin staging infrastructure in terraform/application/pastebin (e.g. RDS MySql database & some AWS secrets - metadata only, values added by operator)
* moves (and only moves) cluster & shared infrastructure into terraform/shared
* next steps: will need to ensure itse-apps-stage-1 nodegroup role can connect to the above mysql db (still investigating best way to do this within our upstream rds module)

Why this PR:
* this is not a priority, but as it was low hanging & not time-consuming fruit during the work for another topic, here it is. if nobody has time to review it, this can sit.
* adds pastebin stage infra & sets pattern for next few applications

### CODE REVIEW

**Review by duallain — COMMENTED** [review]
of the two options available, I prefer the other option (2).  Most of the issues I've been having is with how many tf directories we have, and this change seems to continue that issue.

**Comment by sciurus** [comment]
Of the two options, my vote is for this one.

I think it's valuable to modularize terraform, both to limit the blast radius and to make it easier to work on. I don't think the cluster definition should be in the same module as application resources, and I don't think resources for one application should be in the same module as resources for another application.

My only concern with this option is that you'll have to copy-and-paste the pastebin module verbatim into the [itse-apps-prod-1-infra](https://github.com/mozilla-it/itse-apps-prod-1-infra) repo. I wonder if we could solve that by having an applications directory in our [terraform-modules](https://github.com/mozilla-it/terraform-modules) where the pastebin module lives, and then reference it from each k8s cluster repo?

That's not as nice as having all the terraform code in one repo, but might be a good compromise given we currently have separate repos for each cluster.

**Comment by cmharlow** [comment]
replying to @sciurus 
> 
> My only concern with this option is that you'll have to copy-and-paste the pastebin module from here into the [itse-apps-prod-1-infra](https://github.com/mozilla-it/itse-apps-prod-1-infra) repo. I wonder if we could solve that by having an applications directory in our [terraform-modules](https://github.com/mozilla-it/terraform-modules) where the pastebin module lives, and then reference it from each k8s cluster repo? That's not as nice as having all the terraform code in one repo, but might be a good compromise given we currently have separate repos for each cluster.

So, ideally (to me), we'd get to a place where we don't have itse-apps-{env}-1-infra separated into git repo per environment, and instead use an internal modules directory & workspaces to update one environment than the other in the same repository & using the same code.

I'm hesitant to throw this dpaste application infra into tf modules, bc they really aren't requiring of a tf module (or a github repo on its own, hence the original move).

**Comment by cmharlow** [comment]
Per team conversation, moving forward with this option.

**Pull request merged**
